#!/bin/sh

if command -v pass &>/dev/null && command -v pass-otp &>/dev/null; then

dir="${PASSWORD_STORE_DIR}"

choice="$({ echo "🆕add" ; echo "🕙sync-time" ; ls "$dir"/*-otp.gpg ;} | sed "s/.*\///;s/-otp.gpg//" | dmenu -p "Pick a 2FA:")"



case $choice in
	🆕add )
		if command -v maim &>/dev/null && command -v zbar &>/dev/null; then

		temp=$(mktemp -p "$XDG_RUNTIME_DIR" --suffix=.png)
		otp="otp-test-script"
		trap 'rm -f $temp; pass rm -f $otp' HUP INT QUIT TERM PWR EXIT

		notify-send "Scan the image." "Scan the OTP QR code."

		maim -s "$temp" || exit 1
		info="$(zbarimg -q "$temp")"
		info="${info#QR-Code:}"

		if echo "$info" | pass otp insert "$otp"; then
			while true ; do
				export name="$(echo | dmenu -p "Give this One Time Password a one-word name:")"
				echo "$name" | grep -q -- "^[A-z0-9-]\+$" && break
			done
			pass mv "$otp" "$name-otp"
			notify-send "Successfully added." "$name-otp has been created."
		else
			notify-send "No OTP data found." "Try to scan the image again more precisely."
		fi
		;;
	🕙sync-time )
		if command -v ntp &>/dev/null; then
			notify-send -u low "🕙 Synchronizing Time..." "Synching time with remote NTP servers..."
			updatedata="$(sudo ntpdate pool.ntp.org)" &&
			notify-send -u low "🕙 Synchronizing Time..." "Done. Time changed by ${updatedata#*offset }"
		fi
		;;
	*)
		pass otp -c ${choice}-otp
		;;
esac

