#!/bin/bash

if [ $# -lt 1 ]; then
  echo "Usage: $0 [-v] <directory>"
  exit 1
fi

verbose=false

# Check if the -v flag is provided
if [ "$1" == "-v" ]; then
  verbose=true
  shift
fi

directory="$1"

# Check if the directory exists
if [ ! -d "$directory" ]; then
  echo "Directory does not exist."
  exit 1
fi

# Function to generate a random number
generate_random_number() {
  length="$1"
  echo $(cat /dev/urandom | tr -dc '0-9' | head -c "$length")
}

# Function to shred files in a directory and its subdirectories
shred_directory() {
  local dir="$1"
  for file in "$dir"/*; do
    if [ -d "$file" ]; then
      # If it's a directory, recursively process it
      shred_directory "$file"
      # Generate a random number and rename the directory
      new_name="$(generate_random_number ${#dir})"
      sudo mv "$file" "$dir/$new_name"
      sudo mv "$file" "$new_name"
      if [ "$verbose" = true ]; then
        echo "Changed directory name to $new_name"
      fi
    else
      # If it's a file, shred it
      if [ "$verbose" = true ]; then
        sudo shred -fvuz "$file"
      else
        sudo shred -fuz "$file"
      fi
    fi
  done
}

# Start shredding the directory and its subdirectories
shred_directory "$directory"

# Generate a random number and rename the directory
new_name="$(generate_random_number ${#directory})"
sudo mv "$directory" "$new_name"

# Remove the final directory
rm -rf "$new_name"

echo "Directory and its contents have been renamed and shredded."

# Check if verbose mode is enabled and add "read -r lol" if true
if [ "$verbose" = true ]; then
  read -r lol
  clear
fi
